apiVersion: v1
kind: Service

metadata:
  name: {{.Release.Name}}-service

spec:
  type: {{.Values.service.type}}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT | default 8000 }}
      # nodePort: {{ .Values.service.nodePort }}
    
  selector:
    app: videotube
