# CICD using GitHub Actions for Express.js Project

name: videotube-ci-cd

on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: webpack --config webpack.config.cjs --mode production

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint for Code Quality
        run: npm run lint

  docker-hub:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aws-cicd-videotube:${{ github.run_id }}

  update-image-tag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: docker-hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VIDEOTUBE_AWS_CICD_TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/videotube/vt-ingress/values.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.email "navrajsingh.dev@gmail.com"
          git config --global user.name "navraj-singh-dev"
          git add helm/videotube/vt-ingress/values.yaml
          git commit -m "Update image tag in Helm chart"
          git push
